version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: korious
      POSTGRES_PASSWORD: freedom
      POSTGRES_DB: CRUD APP
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:freedom@localhost:5432/CRUD APP

volumes:
  postgres_data:
